------------------------------------ BI -------------------------------------------

--Crear Tabla bi_tiempo
CREATE TABLE GRUPO_123.bi_tiempo(
TIEMPO_CODIGO INT PRIMARY KEY IDENTITY,
ANIO INT,
CUATRIMESTRE INT,
MES INT
)
go
-- Insertar en la tabla bi_tiempo
INSERT INTO GRUPO_123.bi_tiempo(ANIO, CUATRIMESTRE, MES)
select distinct YEAR(FACTURA_FECHA), DATEPART(QUARTER, FACTURA_FECHA), MONTH(FACTURA_FECHA)
	from GRUPO_123.Factura
	union
	select distinct YEAR(ENVIO_FECHA_ENTREGA), DATEPART(QUARTER, ENVIO_FECHA_ENTREGA), MONTH(ENVIO_FECHA_ENTREGA)
	FROM GRUPO_123.Envio
	union
	select distinct YEAR(ENVIO_FECHA_PROGRAMADA), DATEPART(QUARTER, ENVIO_FECHA_PROGRAMADA), MONTH(ENVIO_FECHA_PROGRAMADA)
	FROM GRUPO_123.Envio
	union
	select distinct YEAR(PUBLICACION_FECHA_FIN), DATEPART(QUARTER, PUBLICACION_FECHA_FIN), MONTH(PUBLICACION_FECHA_FIN)
	FROM GRUPO_123.Publicacion
	union
	select distinct YEAR(PUBLICACION_FECHA_INICIO), DATEPART(QUARTER, PUBLICACION_FECHA_INICIO), MONTH(PUBLICACION_FECHA_INICIO)
	FROM GRUPO_123.Publicacion
	union
	select distinct YEAR(PAGO_FECHA), DATEPART(QUARTER, PAGO_FECHA), MONTH(PAGO_FECHA)
	FROM GRUPO_123.Pago
	union
	select distinct YEAR(VENTA_FECHA), DATEPART(QUARTER, VENTA_FECHA), MONTH(VENTA_FECHA)
	FROM GRUPO_123.Venta
	order by 1 desc, 3 asc
go
------------------------------------------------------------------------------------------------------------------------------
--Crear Tabla bi_ubicacion
CREATE TABLE GRUPO_123.bi_ubicacion(
UBICACION_CODIGO INT PRIMARY KEY IDENTITY,
PROVINCIA NVARCHAR(50),
LOCALIDAD NVARCHAR(50)
)
go
--Insertar en Tabla bi_ubicacion
INSERT INTO GRUPO_123.bi_ubicacion(PROVINCIA, LOCALIDAD)
SELECT DISTINCT PROVINCIA_NOMBRE, LOCALIDAD_NOMBRE FROM GRUPO_123.Localidad JOIN GRUPO_123.Provincia ON PROVINCIA_CODIGO = LOCALIDAD_PROVINCIA
go
------------------------------------------------------------------------------------------------------------------------------

--Crear Tabla bi_rango_etario_cliente
CREATE TABLE GRUPO_123.bi_rango_etario_cliente(
	RANGO_ETARIO_CODIGO INT PRIMARY KEY IDENTITY,
	EDAD_MINIMA INT,
	EDAD_MAXIMA INT
)
go
--Insertar en Tabla bi_rango_etario_cliente
INSERT INTO  GRUPO_123.bi_rango_etario_cliente(EDAD_MINIMA, EDAD_MAXIMA) VALUES (0,25), (25,35), (35,50), (50,150), (NULL,NULL)
go
------------------------------------------------------------------------------------------------------------------------------

--Crear Tabla bi_horario_venta
CREATE TABLE GRUPO_123.bi_horario_venta(
	HORARIO_VENTA_CODIGO INT PRIMARY KEY IDENTITY,
	HORARIO_INICIO INT,
	HORARIO_FIN INT
)
go
--Insertar en Tabla bi_horario_venta
INSERT INTO GRUPO_123.bi_horario_venta(HORARIO_INICIO ,HORARIO_FIN) VALUES(0,6), (6, 12), (12, 18), (18, 24)
go
------------------------------------------------------------------------------------------------------------------------------

--Crear Tabla bi_tipo_medio_pago
CREATE TABLE GRUPO_123.bi_tipo_medio_pago(
	TIPO_MEDIO_PAGO_CODIGO INT PRIMARY KEY IDENTITY,
	TIPO_MEDIO_PAGO NVARCHAR(50)
)
go
--Insertar en Tabla bi_tipo_medio_pago
INSERT INTO GRUPO_123.bi_tipo_medio_pago(TIPO_MEDIO_PAGO)
SELECT DISTINCT MEDIO_PAGO_TIPO FROM GRUPO_123.Medio_Pago
go
------------------------------------------------------------------------------------------------------------------------------

--Crear Tabla bi_tipo_envio
CREATE TABLE GRUPO_123.bi_tipo_envio (
	TIPO_ENVIO_CODIGO INT PRIMARY KEY IDENTITY,
	TIPO_ENVIO NVARCHAR(50)
)
go
--Insertar en Tabla bi_tipo_envio
INSERT INTO GRUPO_123.bi_tipo_envio(TIPO_ENVIO)
SELECT DISTINCT TIPO_ENVIO_DESCRIPCION FROM GRUPO_123.Tipo_Envio
go
------------------------------------------------------------------------------------------------------------------------------

--Crear Tabla bi_rubro_subrubro
CREATE TABLE GRUPO_123.bi_rubro_subrubro(
	RUBRO_SUBRUBRO_CODIGO INT PRIMARY KEY IDENTITY,
	SUBRUBRO NVARCHAR(50),
	RUBRO NVARCHAR(50)
)
go
--Insertar en Tabla bi_rubro_subrubro
INSERT INTO  GRUPO_123.bi_rubro_subrubro(SUBRUBRO, RUBRO)
SELECT DISTINCT SUB_RUBRO_DESCRIPCION, RUBRO_DESCRIPCION FROM GRUPO_123.Producto
JOIN GRUPO_123.Sub_Rubro ON PRODUCTO_SUB_RUBRO = SUB_RUBRO_CODIGO
JOIN GRUPO_123.Rubro ON RUBRO_CODIGO = SUB_RUBRO_RUBRO
JOIN GRUPO_123.Publicacion ON PUBLICACION_PRODUCTO = PRODUCTO_ID
go
-------------------------------------------------------------------------------------------------------------------------------------------
-- Crear Tabla bi_publicacion (completa)

CREATE TABLE GRUPO_123.bi_publicacion( --AGREGAR FKS
	PUBLICACION_CODIGO decimal(18,0) PRIMARY KEY,
    TIEMPO_INICIAL INT, --(id)
    TIEMPO_FINAL INT, --(id)
    RUBRO_SUBRUBRO_CODIGO INT,-- (id)
	STOCK_INICIAL decimal(18,0),
	DURACION_EN_DIAS INT,
	UBICACION_VENDEDOR_CODIGO int,
	MARCA nvarchar(50),
	FOREIGN KEY (TIEMPO_INICIAL) REFERENCES GRUPO_123.bi_tiempo(TIEMPO_CODIGO),
	FOREIGN KEY (TIEMPO_FINAL) REFERENCES GRUPO_123.bi_tiempo(TIEMPO_CODIGO),
	FOREIGN KEY (RUBRO_SUBRUBRO_CODIGO) REFERENCES GRUPO_123.bi_rubro_subrubro(RUBRO_SUBRUBRO_CODIGO),
	FOREIGN KEY (UBICACION_VENDEDOR_CODIGO) REFERENCES GRUPO_123.bi_ubicacion(UBICACION_CODIGO)
)
GO


-- Insertar datos en bi_publicacion
INSERT INTO GRUPO_123.bi_publicacion(PUBLICACION_CODIGO,TIEMPO_INICIAL, TIEMPO_FINAL, RUBRO_SUBRUBRO_CODIGO, STOCK_INICIAL, DURACION_EN_DIAS, UBICACION_VENDEDOR_CODIGO, MARCA)
SELECT 
	P.PUBLICACION_CODIGO,
    T1.TIEMPO_CODIGO AS TIEMPO_INICIAL,
    T2.TIEMPO_CODIGO AS TIEMPO_FINAL,
    RSR.RUBRO_SUBRUBRO_CODIGO,
	P.PUBLICACION_STOCK + isnull((
		select sum(ISNULL(DETALLE_VENTA_CANTIDAD, 0)) from GRUPO_123.Detalle_Venta
		where DETALLE_VENTA_PUBLICACION = P.PUBLICACION_CODIGO),0
	),
	DATEDIFF(DAY, P.PUBLICACION_FECHA_INICIO, P.PUBLICACION_FECHA_FIN),
	UBICACION_CODIGO,
	PROD.PRODUCTO_MARCA
FROM GRUPO_123.Publicacion P
JOIN GRUPO_123.bi_tiempo T1 
    ON YEAR(P.PUBLICACION_FECHA_INICIO) = T1.ANIO AND MONTH(P.PUBLICACION_FECHA_INICIO) = T1.MES
JOIN GRUPO_123.bi_tiempo T2 
    ON YEAR(P.PUBLICACION_FECHA_FIN) = T2.ANIO AND MONTH(P.PUBLICACION_FECHA_FIN) = T2.MES
JOIN GRUPO_123.Producto PROD 
    ON P.PUBLICACION_PRODUCTO = PROD.PRODUCTO_ID
JOIN GRUPO_123.Sub_Rubro SR
	ON PRODUCTO_SUB_RUBRO = SUB_RUBRO_CODIGO
JOIN GRUPO_123.Rubro R
	ON SUB_RUBRO_RUBRO = RUBRO_CODIGO
JOIN GRUPO_123.bi_rubro_subrubro RSR 
    ON R.RUBRO_DESCRIPCION = RSR.RUBRO AND SR.SUB_RUBRO_DESCRIPCION = RSR.SUBRUBRO
JOIN GRUPO_123.Vendedor ON PUBLICACION_VENDEDOR = VENDEDOR_CUIT
JOIN GRUPO_123.Usuario ON VENDEDOR_USUARIO = USUARIO_CODIGO
JOIN GRUPO_123.Domicilio ON USUARIO_DOMICILIO = DOMICILIO_CODIGO
JOIN GRUPO_123.Localidad ON DOMICILIO_LOCALIDAD = LOCALIDAD_CODIGO
JOIN GRUPO_123.Provincia ON LOCALIDAD_PROVINCIA = PROVINCIA_CODIGO
JOIN GRUPO_123.bi_ubicacion ON PROVINCIA = PROVINCIA_NOMBRE AND LOCALIDAD = LOCALIDAD_NOMBRE

GO
-------------------------------------------------------------------------------------------------------------

CREATE TABLE GRUPO_123.bi_cliente(
	ID_CLIENTE int primary key identity,
	DNI decimal(18,0),
	NOMBRE nvarchar(50),
	APELLIDO nvarchar(50),
	ID_GRUPO_ETARIO INT,
	ID_UBICACION INT,
	FOREIGN KEY (ID_GRUPO_ETARIO) REFERENCES GRUPO_123.bi_rango_etario_cliente(RANGO_ETARIO_CODIGO),
	FOREIGN KEY (ID_UBICACION) REFERENCES GRUPO_123.bi_ubicacion(UBICACION_CODIGO)
)
go

insert into GRUPO_123.bi_cliente (DNI, NOMBRE,APELLIDO, ID_GRUPO_ETARIO, ID_UBICACION)
SELECT CLIENTE_DNI, CLIENTE_NOMBRE, CLIENTE_APELLIDO, RANGO_ETARIO_CODIGO, UBICACION_CODIGO
FROM GRUPO_123.Cliente
JOIN GRUPO_123.Usuario ON CLIENTE_USUARIO = USUARIO_CODIGO
JOIN GRUPO_123.Domicilio ON USUARIO_DOMICILIO = DOMICILIO_CODIGO
JOIN GRUPO_123.Localidad ON LOCALIDAD_CODIGO = DOMICILIO_LOCALIDAD
JOIN GRUPO_123.Provincia ON LOCALIDAD_PROVINCIA = PROVINCIA_CODIGO
JOIN GRUPO_123.bi_ubicacion ON LOCALIDAD_NOMBRE = LOCALIDAD AND PROVINCIA_NOMBRE = PROVINCIA
JOIN GRUPO_123.bi_rango_etario_cliente ON DATEDIFF(YEAR, CLIENTE_FECHA_NAC, GETDATE()) >= EDAD_MINIMA 
									   AND DATEDIFF(YEAR, CLIENTE_FECHA_NAC, GETDATE()) < EDAD_MAXIMA

---------------------------------------------------------------------------------------------------------------

CREATE TABLE GRUPO_123.bi_ventas(
	VENTA_ID decimal(18, 0) primary key,
	ID_TIEMPO INT,
	ID_UBICACION_ALMACEN INT,
	VENTA_CANTIDAD decimal(18,0),
	VENTA_TOTAL decimal(18,2),
	VENTA_PUBLICACION  decimal(18,0),
	VENTA_CLIENTE int,
	VENTA_MEDIO_PAGO INT,
	VENTA_CANTIDAD_CUOTA decimal(18,0),
	VENTA_PAGO_IMPORTE decimal(18,2)
	FOREIGN KEY (ID_TIEMPO) REFERENCES GRUPO_123.bi_tiempo(TIEMPO_CODIGO),
	FOREIGN KEY (ID_UBICACION_ALMACEN) REFERENCES GRUPO_123.bi_ubicacion(UBICACION_CODIGO),
	FOREIGN KEY (VENTA_PUBLICACION) REFERENCES GRUPO_123.bi_publicacion(PUBLICACION_CODIGO),
	FOREIGN KEY (VENTA_CLIENTE) REFERENCES GRUPO_123.bi_cliente(ID_CLIENTE),
	FOREIGN KEY (VENTA_MEDIO_PAGO) REFERENCES GRUPO_123.bi_tipo_medio_pago(TIPO_MEDIO_PAGO_CODIGO)
)
go
insert into GRUPO_123.bi_ventas(VENTA_ID, ID_TIEMPO, ID_UBICACION_ALMACEN,VENTA_CANTIDAD, VENTA_TOTAL, VENTA_PUBLICACION, VENTA_CLIENTE, VENTA_MEDIO_PAGO, VENTA_CANTIDAD_CUOTA, VENTA_PAGO_IMPORTE)
select VENTA_CODIGO, TIEMPO_CODIGO, UBICACION_CODIGO,DETALLE_VENTA_CANTIDAD, VENTA_TOTAL , PUBLICACION_CODIGO, ID_CLIENTE, TIPO_MEDIO_PAGO_CODIGO, DETALLE_PAGO_CANT_CUOTAS,PAGO_IMPORTE
from GRUPO_123.Venta V
JOIN GRUPO_123.Detalle_Venta ON VENTA_CODIGO = DETALLE_VENTA_VENTA
JOIN GRUPO_123.Publicacion ON DETALLE_VENTA_PUBLICACION = PUBLICACION_CODIGO
JOIN GRUPO_123.Almacenes ON PUBLICACION_ALMACEN = ALMACEN_CODIGO
JOIN GRUPO_123.Localidad ON ALMACEN_LOCALIDAD = LOCALIDAD_CODIGO
JOIN GRUPO_123.Provincia ON LOCALIDAD_PROVINCIA = PROVINCIA_CODIGO
JOIN GRUPO_123.bi_ubicacion ON LOCALIDAD_NOMBRE = LOCALIDAD AND PROVINCIA_NOMBRE = PROVINCIA
JOIN GRUPO_123.bi_tiempo ON YEAR(VENTA_FECHA) = ANIO AND MONTH(VENTA_FECHA) = MES
JOIN GRUPO_123.bi_cliente C ON V.VENTA_CLIENTE_DNI = C.DNI AND V.VENTA_CLIENTE_NOMBRE+V.VENTA_CLIENTE_APELLIDO = C.NOMBRE+C.APELLIDO
JOIN GRUPO_123.Pago ON PAGO_VENTA = VENTA_CODIGO
JOIN GRUPO_123.Medio_Pago On PAGO_MEDIO_PAGO = MEDIO_PAGO_CODIGO
JOIN GRUPO_123.bi_tipo_medio_pago ON MEDIO_PAGO_TIPO = TIPO_MEDIO_PAGO
JOIN GRUPO_123.Detalle_Pago ON PAGO_DETALLE_PAGO = DETALLE_PAGO_TARJETA_CODIGO
GO

CREATE TABLE GRUPO_123.bi_envio(
	ENVIO_CODIGO INT PRIMARY KEY,
	ENVIO_FECHA_PROGRAMADA date,
	ENVIO_FECHA_ENTREGA datetime,
	ENVIO_HORA_INICIO decimal(18, 0),
	ENVIO_HORA_FIN decimal(18, 0),
	ENVIO_COSTO decimal(18,2),
	ENVIO_VENTA decimal(18, 0),
	ENVIO_UBICACION INT,
	FOREIGN KEY (ENVIO_VENTA) REFERENCES GRUPO_123.bi_ventas(VENTA_ID),
	FOREIGN KEY (ENVIO_UBICACION) REFERENCES GRUPO_123.bi_ubicacion(UBICACION_CODIGO)
)
INSERT INTO GRUPO_123.bi_envio(ENVIO_CODIGO, ENVIO_FECHA_PROGRAMADA, ENVIO_FECHA_ENTREGA, ENVIO_HORA_INICIO, ENVIO_HORA_FIN, ENVIO_COSTO, ENVIO_VENTA, ENVIO_UBICACION)
SELECT ENVIO_NUMERO, ENVIO_FECHA_PROGRAMADA, ENVIO_FECHA_ENTREGA, ENVIO_HORA_INICIO, ENVIO_HORA_FIN, ENVIO_COSTO, VENTA_ID, UBICACION_CODIGO FROM GRUPO_123.Envio
join GRUPO_123.bi_ventas on ENVIO_VENTA = VENTA_ID
join GRUPO_123.Domicilio on ENVIO_DOMICILIO = DOMICILIO_CODIGO
JOIN GRUPO_123.Localidad ON DOMICILIO_LOCALIDAD = LOCALIDAD_CODIGO
JOIN GRUPO_123.Provincia ON LOCALIDAD_PROVINCIA = PROVINCIA_CODIGO
join GRUPO_123.bi_ubicacion on LOCALIDAD_NOMBRE = LOCALIDAD AND PROVINCIA_NOMBRE = PROVINCIA

go
CREATE TABLE GRUPO_123.bi_tipo_factura(
TIPO_CODIGO INT PRIMARY KEY,
TIPO_DESCRIPCION varchar(50)
)
INSERT INTO GRUPO_123.bi_tipo_factura(TIPO_CODIGO, TIPO_DESCRIPCION)
SELECT TIPO_DET_FACT_CODIGO, TIPO_DET_FACT_TIPO FROM GRUPO_123.Tipo_Detalle_Factura

CREATE TABLE GRUPO_123.bi_factura(
FACTURA_ID int PRIMARY KEY IDENTITY,
FACTURA_NUMERO decimal(18,0),
FACTURA_TIPO INT,
FACTURA_FECHA date,
FACTURA_TOTAL decimal(18,0),
FACTURA_PUBLICACION decimal(18, 0),
FOREIGN KEY (FACTURA_TIPO) REFERENCES GRUPO_123.bi_tipo_factura(TIPO_CODIGO),
FOREIGN KEY (FACTURA_PUBLICACION) REFERENCES GRUPO_123.bi_publicacion(PUBLICACION_CODIGO)
)
GO
INSERT INTO GRUPO_123.bi_factura(FACTURA_NUMERO, FACTURA_TIPO,FACTURA_FECHA, FACTURA_TOTAL, FACTURA_PUBLICACION)
SELECT FACTURA_NUMERO, TIPO_CODIGO,FACTURA_FECHA, FACTURA_TOTAL,FACTURA_DET_PUBLICACION FROM GRUPO_123.Factura
JOIN GRUPO_123.Detalle_Factura ON FACTURA_DET_FACTURA = FACTURA_NUMERO
JOIN GRUPO_123.Tipo_Detalle_Factura ON TIPO_DET_FACT_CODIGO = FACTURA_DET_TIPO
JOIN GRUPO_123.bi_tipo_factura ON TIPO_CODIGO = TIPO_DET_FACT_CODIGO


-------------------------------------------------------------------------------------------------------
-- VISTAS

------ VISTA 1 ------
CREATE VIEW GRUPO_123.v_tiempo_promedio_publicacion
AS
SELECT 
    RS.SUBRUBRO AS SubRubro,
    T1.ANIO AS Anio,
    T1.CUATRIMESTRE AS Cuatrimestre,
    AVG(P.DURACION_EN_DIAS) AS TiempoPromedioDias
FROM GRUPO_123.bi_publicacion P
JOIN GRUPO_123.bi_rubro_subrubro RS 
    ON P.RUBRO_SUBRUBRO_CODIGO = RS.RUBRO_SUBRUBRO_CODIGO
JOIN GRUPO_123.bi_tiempo T1
    ON T1.TIEMPO_CODIGO = TIEMPO_INICIAL
JOIN GRUPO_123.bi_tiempo T2
    ON T2.TIEMPO_CODIGO = TIEMPO_FINAL
GROUP BY RS.SUBRUBRO, T1.ANIO, T1.CUATRIMESTRE
GO

------ VISTA 2 ------
CREATE VIEW GRUPO_123.v_StockPromedioPorMarcaYAnio
AS
SELECT 
    BP.MARCA AS Marca,
    T.ANIO AS Anio,
    AVG(BP.STOCK_INICIAL) AS StockPromedio
FROM 
    GRUPO_123.bi_publicacion BP
JOIN 
    GRUPO_123.bi_tiempo T 
    ON BP.TIEMPO_INICIAL = T.TIEMPO_CODIGO
GROUP BY 
    BP.MARCA, T.ANIO
GO

------ VISTA 3 ------
CREATE VIEW GRUPO_123.v_ValorPromedioVentasPorProvinciaYMes
AS
SELECT 
    U.PROVINCIA AS Provincia,
    T.ANIO AS Anio,
    T.MES AS Mes,
    SUM(V.VENTA_TOTAL) / COUNT(V.ID_TIEMPO) AS ValorPromedioVentas
FROM 
    GRUPO_123.bi_ventas V
JOIN 
    GRUPO_123.bi_ubicacion U ON V.ID_UBICACION_ALMACEN = U.UBICACION_CODIGO
JOIN 
    GRUPO_123.bi_tiempo T ON V.ID_TIEMPO = T.TIEMPO_CODIGO
GROUP BY 
    U.PROVINCIA, T.ANIO, T.MES

GO

------ VISTA 4 ------
CREATE VIEW GRUPO_123.v_RendimientoDeRubros
AS
SELECT DISTINCT ANIO, CUATRIMESTRE,RUBRO, LOCALIDAD, RANGO_ETARIO_CODIGO 
from GRUPO_123.bi_rubro_subrubro RSR
join GRUPO_123.bi_publicacion P on RSR.RUBRO_SUBRUBRO_CODIGO = P.RUBRO_SUBRUBRO_CODIGO
join GRUPO_123.bi_ventas V on P.PUBLICACION_CODIGO = V.VENTA_PUBLICACION
join GRUPO_123.bi_cliente C on V.VENTA_CLIENTE = C.ID_CLIENTE
join GRUPO_123.bi_rango_etario_cliente on C.ID_GRUPO_ETARIO = RANGO_ETARIO_CODIGO
join GRUPO_123.bi_ubicacion on C.ID_UBICACION = UBICACION_CODIGO
join GRUPO_123.bi_tiempo on V.ID_TIEMPO = TIEMPO_CODIGO
WHERE RSR.RUBRO_SUBRUBRO_CODIGO in (SELECT top 5 RUBRO_SUBRUBRO_CODIGO FROM GRUPO_123.bi_ventas V2
			join GRUPO_123.bi_publicacion P2 on P2.PUBLICACION_CODIGO = V2.VENTA_PUBLICACION
			join GRUPO_123.bi_cliente C2 on V2.VENTA_CLIENTE = C2.ID_CLIENTE
			WHERE ID_TIEMPO = TIEMPO_CODIGO and UBICACION_CODIGO = C2.ID_UBICACION and RANGO_ETARIO_CODIGO = C2.ID_GRUPO_ETARIO
			GROUP BY P2.RUBRO_SUBRUBRO_CODIGO ORDER BY sum(V2.VENTA_CANTIDAD)DESC)
GO

------ VISTA 6 ------
CREATE VIEW GRUPO_123.v_PagoEnCuotas
AS
SELECT TOP 3 ANIO, MES, TIPO_MEDIO_PAGO, LOCALIDAD FROM GRUPO_123.bi_ventas
JOIN GRUPO_123.bi_envio ON VENTA_ID = ENVIO_VENTA
JOIN GRUPO_123.bi_tipo_medio_pago ON VENTA_MEDIO_PAGO = TIPO_MEDIO_PAGO_CODIGO
JOIN GRUPO_123.bi_ubicacion ON UBICACION_CODIGO = ENVIO_UBICACION
JOIN GRUPO_123.bi_tiempo ON ID_TIEMPO = TIEMPO_CODIGO
WHERE VENTA_CANTIDAD_CUOTA > 1
GROUP BY ANIO, MES, TIPO_MEDIO_PAGO, LOCALIDAD
ORDER BY sum(VENTA_PAGO_IMPORTE)
GO

------ VISTA 7 ------
CREATE VIEW GRUPO_123.v_PorcentajeDeCumplimientoDeEnvíos
AS
SELECT year(ENVIO_FECHA_ENTREGA) AS anio, month(ENVIO_FECHA_ENTREGA) AS mes,PROVINCIA,
(SELECT COUNT(*) FROM GRUPO_123.bi_envio E2
	JOIN GRUPO_123.bi_ventas V2 ON V2.VENTA_ID = E2.ENVIO_VENTA
	JOIN GRUPO_123.bi_ubicacion U2 ON U2.UBICACION_CODIGO = V2.ID_UBICACION_ALMACEN
	WHERE DATEDIFF(DAY, ENVIO_FECHA_PROGRAMADA,ENVIO_FECHA_ENTREGA) = 0 
		AND (datepart(hour, ENVIO_FECHA_ENTREGA) BETWEEN ENVIO_HORA_INICIO AND ENVIO_HORA_FIN) 
		AND YEAR(E2.ENVIO_FECHA_ENTREGA) = YEAR(E1.ENVIO_FECHA_ENTREGA) 
		AND MONTH(E2.ENVIO_FECHA_ENTREGA) = MONTH(E1.ENVIO_FECHA_ENTREGA)
		AND U1.PROVINCIA = U2.PROVINCIA) / COUNT(*) * 100 AS porcentaje
FROM GRUPO_123.bi_envio E1
JOIN GRUPO_123.bi_ventas V1 ON V1.VENTA_ID = E1.ENVIO_VENTA
JOIN GRUPO_123.bi_ubicacion U1 ON U1.UBICACION_CODIGO = V1.ID_UBICACION_ALMACEN
GROUP BY year(ENVIO_FECHA_ENTREGA),month(ENVIO_FECHA_ENTREGA),PROVINCIA
GO

------ VISTA 8 ------
CREATE VIEW GRUPO_123.v_LocalidadesQuePaganMayorCostoDeEnvío
AS
select TOP 5 LOCALIDAD from GRUPO_123.bi_ventas
JOIN GRUPO_123.bi_envio ON ENVIO_VENTA = VENTA_ID
JOIN GRUPO_123.bi_ubicacion ON ENVIO_UBICACION = UBICACION_CODIGO
GROUP BY LOCALIDAD
ORDER BY max(ENVIO_COSTO)
GO

------ VISTA 9 ------
CREATE VIEW GRUPO_123.v_PorcentajeDeFacturaciónXConceptoXMesAnio
AS
SELECT TIPO_DESCRIPCION,year(FACTURA_FECHA) AS anio, month(FACTURA_FECHA) AS mes,
SUM(f1.FACTURA_TOTAL) /
(SELECT SUM(f3.FACTURA_TOTAL) FROM GRUPO_123.bi_factura f3 WHERE year(f1.FACTURA_FECHA) = year(f3.FACTURA_FECHA) AND month(f1.FACTURA_FECHA) = month(F3.FACTURA_FECHA))
*100 AS porcentaje_facturacion
FROM GRUPO_123.bi_factura f1
JOIN GRUPO_123.bi_tipo_factura ON TIPO_CODIGO = f1.FACTURA_TIPO
GROUP BY TIPO_DESCRIPCION,year(FACTURA_FECHA), month(FACTURA_FECHA)
GO

------ VISTA 10 ------
CREATE VIEW GRUPO_123.FacturacionPorProvincia
AS
SELECT PROVINCIA, year(FACTURA_FECHA) AS anio, DATEPART(QUARTER, FACTURA_FECHA) AS cuatrimestre ,SUM(FACTURA_TOTAL) AS monto_total FROM GRUPO_123.bi_factura
JOIN GRUPO_123.bi_publicacion p ON FACTURA_PUBLICACION = p.PUBLICACION_CODIGO
JOIN GRUPO_123.bi_ubicacion ON UBICACION_CODIGO = p.UBICACION_VENDEDOR_CODIGO
GROUP BY PROVINCIA, year(FACTURA_FECHA), DATEPART(QUARTER, FACTURA_FECHA)
GO